import React, { useState, useEffect, useRef } from 'react';
import { Layers, Smartphone, Presentation, Download, ArrowRight, ChevronLeft, ChevronRight, RotateCcw, Maximize, Minimize } from 'lucide-react';
import cases from '../../data/uxCases.json';
import './ux.css';

const uxAsset = path => globalThis.__IMK_ASSETS__?.[path] ?? path;

const days = [
  ['Empathize', 'Memahami pengguna', 'Empathy map & catatan wawancara'],
  ['Define', 'Merumuskan masalah', 'Persona & problem statement'],
  ['Ideate', 'Memilih solusi', '5 ide & storyboard'],
  ['Prototype', 'Membuat rancangan', '4 perubahan & 2 skenario'],
  ['Test & Reflect', 'Mengevaluasi rancangan', 'Laporan, refleksi & rencana iterasi'],
];
const profiles = [
  {name:'H S', code:'N1 / K1', role:'Pembeli token', quote:'Saya ingin melihat nominal, biaya admin dan total saat memilih, supaya tidak perlu bolak-balik.', need:'Tahu jumlah uang yang harus dibayar sejak memilih token.', evidence:'Pemilihan nominal belum menampilkan rincian pada area screenshot; tahap berikutnya sudah menampilkan admin dan total.', source:'S06 → S03 → S02'},
  {name:'H A', code:'N2 / K2', role:'Pemantau pesanan', quote:'Saya ingin tahu pesanan mana yang masih berlaku dan kapan harus membuat pesanan baru.', need:'Tahu batas waktu, status, dan tindakan untuk tiap pesanan.', evidence:'Daftar pesanan menampilkan status menunggu; batas waktu ada di detail pembayaran.', source:'S01 / S10 / S02'},
  {name:'A B P', code:'N3 / K3', role:'Pencari transaksi', quote:'Saya ingin tahu riwayat ini berisi transaksi apa dan harus ke mana untuk melihat pesanan yang belum dibayar.', need:'Ada jalan lanjut saat riwayat transaksi kosong.', evidence:'Halaman riwayat kosong belum menampilkan tindakan pada area screenshot.', source:'S11 / S13'},
  {name:'R P', code:'N4 / K4', role:'Pengguna kategori pembayaran', quote:'Jelaskan kode yang harus dipakai, lalu beri pilihan untuk memperbaiki atau meminta bantuan.', need:'Pesan kesalahan menjelaskan cara memperbaiki masukan.', evidence:'Pesan kode tidak ditemukan dan istilah pada tab pembayaran berpotensi membingungkan.', source:'S04 / S05 / S07'},
];
const ideas = [
 ['Ringkasan biaya saat memilih token','Nominal, metode, admin, dan total terlihat bersama.',5,4,4,'Dipilih • K1'],
 ['Status pesanan dengan tindakan','Tampilkan batas waktu dan tombol sesuai status.',5,3,4,'Dipilih • K2–K3'],
 ['Penjelasan kategori pembayaran','Bedakan Token, Tagihan, dan Non Taglis sebelum input.',4,4,3,'Lanjutan • K4'],
 ['Pesan gagal dengan jalan keluar','Beri contoh kode, perbaiki input, atau buka bantuan.',4,4,3,'Lanjutan • K4'],
 ['Prioritas tugas inti di beranda','Dekatkan akses token dan pesanan aktif.',3,4,3,'Lanjutan'],
];
function Section({n, title, children}) {return <section className="free-section"><div className="free-section-title"><span className="sec-num">{n}</span><h3>{title}</h3></div>{children}</section>;}
function Strip({items}) {return <div className="free-dgti-strip">{items.map(([label,title,body],i)=><div key={label} className={`dgti-item ${i===0?'highlight':''}`}><span className="dgti-code">{label}</span><strong className="dgti-head">{title}</strong><p className="dgti-desc">{body}</p></div>)}</div>;}
function ReportLink({day}) {return <a className="ux-download" href={uxAsset(`/ux/laporan/A_3_tugasUXdesain_${day}.pdf`)} download><Download size={16}/>Unduh deliverable Day {day} (PDF)</a>;}

export default function PageUX() {
 const [page,setPage] = useState('proses');
 const [day,setDay] = useState(0);
 const [caseIndex,setCaseIndex] = useState(0);
 const [profile,setProfile] = useState(0);
 const [notes,setNotes] = useState(false);
 const [fullscreen,setFullscreen] = useState(false);
 const root=useRef(null);
 const changeDay=(i)=>{setDay(i);document.querySelector('.imk-main-canvas')?.scrollTo({top:0});};
 useEffect(()=>{const listener=(e)=>{if(page!=='presentasi'||e.target.closest('input,select,textarea,[contenteditable=true]'))return;if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();changeDay(Math.min(4,day+1));}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();changeDay(Math.max(0,day-1));}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[day,page]);
 useEffect(()=>{const listener=()=>setFullscreen(Boolean(document.fullscreenElement));document.addEventListener('fullscreenchange',listener);return()=>document.removeEventListener('fullscreenchange',listener);},[]);
 const p=profiles[profile];
 return <div className="ux-workspace" ref={root}>
  <nav className="tugas1-nav-bar ux-nav" aria-label="Halaman Tugas 2"><div className="tugas1-nav-tabs">{[['proses',Layers,'Proses UX','Day 1–5'],['kasus',Smartphone,'Rancang Ulang','4 Perubahan'],['presentasi',Presentation,'Presentasi','5 Slide']].map(([id,Icon,label,sub])=><button key={id} className={`tugas1-tab-btn ${page===id?'active':''}`} onClick={()=>{setPage(id);changeDay(0);}}><Icon size={20}/><span>{label} <span className="tab-sub-text">({sub})</span></span></button>)}</div><a className="quick-switch-link" href={uxAsset('/ux/TugasUXdesain_Per_Day_Revisi.zip')} download><Download size={16}/><span>Semua Deliverable</span></a></nav>
  {page==='kasus' ? <><div className="free-nav-bar"><button className="free-back-btn" onClick={()=>setPage('proses')}><ChevronLeft size={16}/>Proses UX</button><div className="free-case-switcher">{cases.map((c,i)=><button key={c.after} className={`free-case-tab ${caseIndex===i?'active':''}`} onClick={()=>setCaseIndex(i)}><span className="tab-num">0{i+1}</span><span className="tab-name">{['Biaya lebih awal','Batas pembayaran','Pesanan kedaluwarsa','Riwayat kosong'][i]}</span></button>)}</div></div><div className="free-showcase-canvas"><div className="free-editorial-column"><div className="free-case-headline"><div className="free-meta-line"><span className="free-stage-label">DAY 4 • {cases[caseIndex].code}</span><span className="free-theory-label">{cases[caseIndex].before} → {cases[caseIndex].after}</span></div><h1 className="free-display-title">{['Biaya terlihat sejak memilih token','Batas waktu langsung terlihat','Status berubah, tindakan ikut berubah','Halaman kosong punya jalan lanjut'][caseIndex]}</h1></div><div className="free-narrative-flow">{[['issue','SEBELUM',cases[caseIndex].b],['fix','USULAN PERUBAHAN',cases[caseIndex].a],['result','MANFAAT YANG DIHARAPKAN',cases[caseIndex].reason]].map(([style,label,text])=><div className={`free-narrative-item ${style}`} key={label}><div className="narrative-tag">{label}</div><p className="narrative-text">{text}</p></div>)}</div><div className="free-controls-bar"><span>Perubahan <b>{caseIndex+1}</b> / 4</span><div className="free-btn-group"><button className="free-nav-arrow" aria-label="Perubahan sebelumnya" disabled={caseIndex===0} onClick={()=>setCaseIndex(caseIndex-1)}><ChevronLeft size={18}/></button><button className="free-nav-arrow primary" aria-label="Perubahan berikutnya" disabled={caseIndex===3} onClick={()=>setCaseIndex(caseIndex+1)}><ChevronRight size={18}/></button></div></div></div><div className="free-mockups-stage">{[['asli','SEBELUM • SCREENSHOT',cases[caseIndex].before,'jpeg'],['fiksasi','SESUDAH • RANCANGAN',cases[caseIndex].after,'png']].map(([style,label,code,ext])=><figure className="free-phone-wrapper" key={code}><figcaption className={`free-phone-label ${style}`}><span className="label-status">{label}</span><span className="label-sub">{code}</span></figcaption><img className="ux-screen-image" src={uxAsset(`/ux/${code}.${ext}`)} alt={`${label}: ${cases[caseIndex].title}`}/></figure>)}</div></div></> : <div className="summary-free-canvas ux-body">
   <div className="free-hero-header"><div className="hero-text-block"><span className="free-tagline">TUGAS 2 IMK • {page==='presentasi'?`SLIDE ${day+1} DARI 5`:'USER-CENTERED DESIGN'}</span><h1 className="free-hero-title">{page==='presentasi'?days[day][1]:'Token Jelas: Biaya & Status dalam Satu Alur'}</h1><p className="free-hero-sub">{page==='presentasi'?`Day ${day+1} — ${days[day][0]}. ${days[day][2]}.`:'Bantu pengguna tahu berapa yang dibayar, sampai kapan pesanan berlaku, dan apa yang perlu dilakukan berikutnya.'}</p></div><div className="free-stat-ribbon"><div className="free-stat-unit"><span className="stat-label">APLIKASI</span><strong className="stat-value">PLN Mobile</strong></div><div className="stat-divider"/><div className="free-stat-unit"><span className="stat-label">FOKUS</span><strong className="stat-value text-teal">Biaya & Status</strong></div></div></div>
   {page==='proses'?<div className="free-timeline-track ux-day-track" aria-label="Tahap UX">{days.map(([title,plain],i)=><button key={title} className={`timeline-step-btn ${day===i?'active':''}`} onClick={()=>changeDay(i)} aria-current={day===i?'step':undefined}><span className="step-circle">{i+1}</span><span className="step-title">{title}</span><span className="ux-day-sub">{plain}</span></button>)}</div>:<div className="ux-presentation-controls"><div className="free-btn-group"><button className="free-nav-arrow" aria-label="Slide sebelumnya" disabled={day===0} onClick={()=>changeDay(day-1)}><ChevronLeft size={20}/></button><span>Slide {day+1} / 5</span><button className="free-nav-arrow primary" aria-label="Slide berikutnya" disabled={day===4} onClick={()=>changeDay(day+1)}><ChevronRight size={20}/></button></div><div className="free-btn-group"><button className="free-back-btn" onClick={()=>setNotes(!notes)}>{notes?'Sembunyikan':'Catatan'} pembicara</button><button className="free-back-btn" onClick={async()=>{if(document.fullscreenElement)await document.exitFullscreen();else await root.current.requestFullscreen();}}>{fullscreen?<Minimize size={16}/>:<Maximize size={16}/>}Layar penuh</button></div></div>}
   <div className="ux-source-note">Studi berbasis 13 screenshot PLN Mobile. Profil, tanggapan, waktu, dan skor evaluasi dikembangkan dalam skenario desain.</div>
   {day===0 && <>
    <Section n="01" title="Apa yang dibutuhkan pengguna?"><Strip items={profiles.map(p=>[p.code,p.need,p.role])}/></Section>
    <Section n="02" title="Catatan wawancara dalam skenario"><div className="ux-profile-tabs">{profiles.map((p,i)=><button key={p.name} className={`free-case-tab ${profile===i?'active':''}`} onClick={()=>setProfile(i)}>{p.name} <small>{p.code.split(' / ')[0]}</small></button>)}</div><div className="timeline-active-display"><span className="active-meta-tag">{p.role} • ACUAN {p.source}</span><blockquote className="ux-quote">“{p.quote}”</blockquote><div className="active-columns"><div className="active-col"><span className="col-caption text-blue">Terlihat pada layar</span><p>{p.evidence}</p></div><div className="active-col"><span className="col-caption text-teal">Kebutuhan desain</span><p>{p.need}</p></div></div></div></Section>
    {page==='proses' && <Section n="03" title="Empathy map — memahami sudut pandang pengguna"><Strip items={[
     ['SAYS • UCAPAN','“Totalnya berapa?”','Ingin total sejak memilih; ingin tahu pesanan yang masih berlaku.'],['THINKS • PIKIRAN','“Masih bisa dibayar?”','Apakah admin sudah termasuk? Apa yang masuk ke riwayat?'],['DOES • TINDAKAN','Membandingkan informasi','Memeriksa nominal dan total, tanggal, riwayat, dan jenis kode.'],['FEELS • PERASAAN','Ragu saat informasi tersebar','Hipotesis: lebih tenang jika biaya, waktu, dan langkah lanjut jelas.']]}/></Section>}
   </>}
   {day===1 && <>
    <Section n="01" title="Dua persona — gambaran pengguna yang dibantu"><div className="ux-two-col">{profiles.slice(0,2).map((p,i)=><article className="ux-persona" key={p.name}><span className="dgti-code">PERSONA {i===0?'PRIMER':'SEKUNDER'} • {p.name}</span><h2>{p.role}</h2><p><b>Tujuan:</b> {p.need}</p><p><b>Hambatan:</b> {p.evidence}</p><blockquote>“{p.quote}”</blockquote><span className="ux-small">Profil skenario • {p.code} • {p.source}</span></article>)}</div></Section>
    <Section n="02" title="Problem statement — masalah dari sudut pengguna"><div className="timeline-active-display"><p className="ux-problem">Pengguna PLN Mobile yang membeli token dan memantau pesanan membutuhkan ringkasan biaya sejak memilih nominal serta status dan batas waktu yang jelas, agar bisa menentukan pembayaran dan tindakan berikutnya tanpa mencari ulang informasi di beberapa layar.</p></div></Section>
    <Section n="03" title="Seperti apa rancangan yang berhasil?"><Strip items={[
     ['K1','Paham jumlah pembayaran','Menyebut token Rp5.000 + admin Rp1.750 = total Rp6.750 sebelum membuat pesanan.'],['K2','Paham masa berlaku','Menemukan batas waktu dan membedakan status menunggu dengan kedaluwarsa.'],['K3','Punya langkah berikutnya','Dari riwayat kosong, bisa menuju pesanan aktif atau bantuan.'],['BATAS CAKUPAN','Fokus pada alur token','Kategori pembayaran dan pesan gagal (K4) menjadi peluang lanjutan.']]}/></Section>
   </>}
   {day===2 && <>
    <Section n="01" title="Lima ide, dipilih berdasarkan kebutuhan"><div className="ux-table-wrap"><table className="ux-table"><thead><tr><th>Ide & cara kerja</th><th>D</th><th>F</th><th>V</th><th>Keputusan</th></tr></thead><tbody>{ideas.map(([title,desc,d,f,v,status])=><tr key={title}><td><b>{title}</b><p>{desc}</p></td><td>{d}</td><td>{f}</td><td>{v}</td><td><span className={status.startsWith('Dipilih')?'ux-picked':''}>{status}</span></td></tr>)}</tbody></table></div><p className="ux-small">D = dibutuhkan pengguna; F = bisa diterapkan; V = bernilai bagi layanan. Skala 1–5 merupakan penilaian desain.</p></Section>
    <Section n="02" title="Konsep terpilih: Token Jelas"><div className="timeline-active-display"><span className="active-meta-tag">GABUNGAN IDE 1 + 2</span><p className="ux-problem">Tampilkan biaya saat memilih token. Setelah pesanan dibuat, tampilkan status, batas waktu, dan tindakan yang sesuai.</p><p>Teknik SCAMPER: gabungkan informasi biaya, ubah kartu status, dan majukan ringkasan dalam urutan pembelian.</p></div></Section>
    <Section n="03" title="Storyboard — perjalanan pengguna"><div className="ux-story">{[['Pilih token','H S membuka Beli Token dan menentukan nominal.'],['Pahami biaya','Rp5.000 + Rp1.750 = Rp6.750 terlihat sebelum lanjut.'],['Tinjau pesanan','Periksa pilihan lalu buat pesanan contoh.'],['Pantau status','H A melihat status dan batas pembayaran.'],['Masa berlaku habis','Tombol berubah menjadi Buat Pesanan Baru.'],['Temukan jalan lanjut','Riwayat kosong mengarah ke pesanan aktif atau bantuan.']].map(([title,text],i)=><div className="dgti-item" key={title}><span className="ux-story-number">{i+1}</span><strong className="dgti-head">{title}</strong><p>{text}</p></div>)}</div>{page==='proses'&&<details className="ux-details"><summary>Lihat storyboard visual dari deliverable</summary><img className="ux-document-image" src={uxAsset('/ux/storyboard.png')} alt="Storyboard enam panel: memilih token sampai menemukan bantuan"/></details>}</Section>
   </>}
   {day===3 && <>
    <Section n="01" title="Empat perubahan yang menjawab kebutuhan"><div className="ux-four-screens">{cases.map((c,i)=><button className="ux-screen-card" key={c.after} onClick={()=>{setCaseIndex(i);setPage('kasus');}}><span className="dgti-code">{c.code} • {c.after}</span><img src={uxAsset(`/ux/${c.after}.png`)} alt={c.title}/><strong>{['Biaya lebih awal','Waktu di kartu pesanan','Tindakan saat kedaluwarsa','Jalan dari riwayat kosong'][i]}</strong><span className="ux-small">Lihat sebelum & sesudah →</span></button>)}</div></Section>
    {page==='proses'&&<Section n="02" title="Coba alur dengan data contoh"><div className="ux-two-col"><article className="ux-persona"><span className="dgti-code">SKENARIO A • PEMBELIAN TOKEN</span><ol><li>Buka Beli Token.</li><li>Pilih Rp5.000 dan baca rincian biaya.</li><li>Tinjau pilihan lalu buat pesanan.</li><li>Temukan batas pembayaran.</li><li>Buka Pesanan Aktif untuk melihat status.</li></ol></article><article className="ux-persona"><span className="dgti-code">SKENARIO B • STATUS & PEMULIHAN</span><ol><li>Buka riwayat yang kosong.</li><li>Pilih Lihat Pesanan Aktif.</li><li>Baca status serta batas waktu.</li><li>Ubah keadaan demo ke Kedaluwarsa.</li><li>Buat pesanan baru atau buka bantuan.</li></ol></article></div><TokenDemo/></Section>}
    <p className="ux-small">Rp5.000, admin BCA VA Rp1.750, dan total Rp6.750 mengikuti contoh screenshot. Status kedaluwarsa adalah keadaan rancangan; tanggal pesanan lama saja tidak membuktikan masa berlakunya habis.</p>
   </>}
   {day===4 && <>
    <Section n="01" title="Dua tugas, tiga karakter dalam skenario"><Strip items={[
     ['TUGAS A','Memahami biaya token','Pilih Rp5.000, sebut admin dan total, lalu temukan batas pembayaran.'],['TUGAS B','Memahami status pesanan','Dari riwayat kosong, cari pesanan aktif dan tindakan saat kedaluwarsa.'],['SELESAI MANDIRI','5 dari 6 tugas','Satu tugas memerlukan bantuan untuk memahami kedaluwarsa.'],['KEMUDAHAN','4,0 / 5','Rata-rata skor ilustratif dari enam tugas.']]}/><div className="ux-table-wrap"><table className="ux-table"><thead><tr><th>Karakter</th><th>Tugas A</th><th>Tugas B</th></tr></thead><tbody><tr><td>H S / N1</td><td>Mandiri • 75 detik • 4/5</td><td>Dengan bantuan • 95 detik • 3/5</td></tr><tr><td>H A / N2</td><td>Mandiri • 55 detik • 5/5</td><td>Mandiri • 70 detik • 4/5</td></tr><tr><td>A B P / N3</td><td>Mandiri • 85 detik • 4/5</td><td>Mandiri • 80 detik • 4/5</td></tr></tbody></table></div><p className="ux-small">Waktu, hasil, skor, dan tanggapan adalah ilustrasi skenario, bukan pengukuran sesi pengguna. Rata-rata waktu A: 71,7 detik; B: 81,7 detik.</p></Section>
    <Section n="02" title="Apa yang dipelajari, apa yang diperbaiki?"><div className="ux-two-col"><article className="ux-persona"><span className="dgti-code">REFLEKSI INDIVIDU</span><h2>Informasi harus muncul saat dibutuhkan</h2><p>Saya belajar bahwa masalah desain perlu mengikuti bukti layar. Admin dan total sudah ada sebelum pembayaran; perubahan yang relevan adalah memajukannya ke tahap memilih token.</p><p>Dalam skenario, rincian biaya dan jalan dari riwayat mendukung alur. Penjelasan kedaluwarsa masih membutuhkan bantuan.</p></article><article className="ux-persona"><span className="dgti-code">RENCANA ITERASI • URUTAN PRIORITAS</span><ol><li><b>Perjelas kedaluwarsa:</b> “Batas waktu pembayaran telah habis”, lalu Buat Pesanan Baru.</li><li><b>Dekatkan status dan waktu:</b> tampilkan bersama pada satu kartu.</li><li><b>Pertahankan biaya & jalur lanjut:</b> total di pemilihan token, akses pesanan aktif di riwayat.</li></ol><p className="ux-small">Ini prioritas revisi berikutnya dari evaluasi skenario.</p></article></div></Section>
   </>}
   {notes&&page==='presentasi'&&<aside className="ux-speaker-note"><b>Catatan pembicara</b><p>{[
    'UX adalah pengalaman saat memakai aplikasi. Di sini saya mulai dari kebutuhan: berapa yang dibayar, apakah pesanan masih berlaku, dan ke mana harus pergi saat riwayat kosong. Profil ini dikembangkan dalam skenario dari screenshot.',
    'Persona adalah gambaran pengguna yang menjadi fokus desain. H S ingin kepastian biaya; H A ingin kepastian status. Masalahnya adalah informasi yang harus dicari di beberapa layar.',
    'Saya membandingkan lima ide. Dua ide pertama digabung karena biaya membantu sebelum membuat pesanan dan status membantu sesudahnya. Skor merupakan pertimbangan desain.',
    'Perhatikan empat layar. Total dimajukan ke pemilihan nominal, waktu diletakkan di kartu pesanan, kedaluwarsa punya tindakan baru, dan riwayat kosong punya jalan lanjut. Klik layar untuk membandingkan.',
    'Evaluasi ini berbasis skenario tiga karakter dengan dua tugas. Angkanya ilustratif. Satu tugas memerlukan bantuan untuk memahami kedaluwarsa, sehingga penjelasan status menjadi prioritas iterasi.'
   ][day]}</p></aside>}
   <div className="free-bottom-cta"><div className="cta-statement"><strong>Day {day+1} — {days[day][0]}</strong><span>Deliverable: {days[day][2]}</span></div><div className="ux-bottom-actions"><ReportLink day={day+1}/>{day<4&&<button className="free-cta-btn" onClick={()=>changeDay(day+1)}>Day {day+2}<ArrowRight size={17}/></button>}{day===4&&<a className="ux-download" href={uxAsset('/ux/laporan/A_3_tugasUXdesain_5_Presentasi.pdf')} download>Presentasi 5 slide (PDF)<Download size={16}/></a>}</div></div>
  </div>}
 </div>;
}

function TokenDemo(){
 const [screen,setScreen]=useState('home');const [amount,setAmount]=useState(0);const [expired,setExpired]=useState(false);const [created,setCreated]=useState(false);const [history,setHistory]=useState([]);
 const go=(next)=>{setHistory(h=>[...h,screen]);setScreen(next);};
 const back=()=>{if(history.length){setScreen(history[history.length-1]);setHistory(h=>h.slice(0,-1));}};
 const reset=()=>{setScreen('home');setAmount(0);setExpired(false);setCreated(false);setHistory([]);};
 const rupiah=(n)=>'Rp'+n.toLocaleString('id-ID');
 const total=amount+1750;
 const row=(label,value)=><div className="ux-demo-row"><span>{label}</span><b>{value}</b></div>;
 return <div className="ux-demo-layout"><div className="ux-demo-guide"><span className="dgti-code">PROTOTIPE INTERAKTIF • DATA CONTOH</span><h2>Peragakan biaya, status, dan langkah berikutnya.</h2><p>Pilihan nominal tersimpan saat kembali. Pesanan dibuat setelah meninjau total. Pembayaran dan penerbitan token tidak dilakukan dalam demo ini.</p><p><b>Coba:</b> beli token Rp5.000, lalu buka pesanan aktif. Ubah keadaan untuk memperagakan masa pembayaran yang habis.</p><button className="free-back-btn" onClick={reset}><RotateCcw size={16}/>Ulangi demo</button><label className="ux-demo-toggle"><input type="checkbox" checked={expired} onChange={e=>setExpired(e.target.checked)}/>Keadaan demo: kedaluwarsa</label></div><div className="ux-demo-phone"><div className="ux-demo-status">09:41 <span>●●● ▰</span></div><div className="ux-demo-top"><button onClick={back} disabled={!history.length} aria-label="Kembali di prototipe"><ChevronLeft size={20}/></button><strong>{ {home:'PLN Mobile',choose:'Token & Pembayaran',review:'Tinjau Pesanan',payment:'Detail Pembayaran',active:'Pesanan Aktif',history:'Riwayat Transaksi',help:'Bantuan Pembayaran'}[screen]}</strong></div><div className="ux-demo-content">
 {screen==='home'&&<><div className="ux-demo-card"><span className="ux-small">PELANGGAN CONTOH</span><h3>H S • Rumah</h3><p>12345678901 / Prabayar</p></div><h2>Mau melakukan apa?</h2><button onClick={()=>go('choose')}>Beli Token</button><button className="secondary" onClick={()=>go('active')}>Pesanan Aktif</button><button className="secondary" onClick={()=>go('history')}>Riwayat & Bantuan</button></>}
 {screen==='choose'&&<><div className="ux-demo-card">ID contoh: <b>12345678901</b></div><h3>Pilih nominal token</h3><div className="ux-demo-options">{[5000,10000,20000,50000].map(n=><button key={n} className={amount===n?'selected':'secondary'} onClick={()=>setAmount(n)} aria-pressed={amount===n}>{rupiah(n)}</button>)}</div><div className="ux-demo-card">Metode: <b>BCA Virtual Account</b></div>{amount>0?<div className="ux-demo-card">{row('Nominal',rupiah(amount))}{row('Admin','Rp1.750')}{row('Total pembayaran',rupiah(total))}</div>:<p>Pilih nominal untuk melihat admin dan total pembayaran.</p>}<button disabled={!amount} onClick={()=>go('review')}>Selanjutnya</button></>}
 {screen==='review'&&<><div className="ux-demo-card"><h3>Periksa sebelum lanjut</h3>{row('Token',rupiah(amount))}{row('BCA VA / Admin','Rp1.750')}{row('Total',rupiah(total))}</div><p>Langkah ini membuat pesanan. Pembayaran belum dilakukan.</p><button className="secondary" onClick={()=>go('choose')}>Ubah Pilihan</button><button onClick={()=>{setCreated(true);setExpired(false);go('payment');}}>Lanjutkan Pembayaran</button></>}
 {screen==='payment'&&<><div className="ux-demo-card"><h3>{expired?'Kedaluwarsa':'Menunggu Pembayaran'}</h3><p>{expired?'Batas waktu pembayaran telah habis.':'Sisa waktu contoh: 03:16:40'}</p>{row('Total',rupiah(total))}</div>{!expired&&<div className="ux-demo-card"><span>Virtual Account contoh</span><h3>000000000000</h3><p>Nomor dummy untuk demonstrasi.</p></div>}<button onClick={()=>go(expired?'choose':'active')}>{expired?'Buat Pesanan Baru':'Lihat Pesanan Aktif'}</button></>}
 {screen==='active'&&<>{created?<><div className="ux-demo-card">{row('P-001 • Token',rupiah(amount))}<h3 className={expired?'ux-expired':'text-teal'}>{expired?'Kedaluwarsa':'Menunggu pembayaran'}</h3><p>{expired?'Batas waktu pembayaran telah habis. Pesanan ini tidak dapat dibayar.':'Sisa waktu contoh: 03:16:40'}</p>{row('Total',rupiah(total))}<button onClick={()=>go(expired?'choose':'payment')}>{expired?'Buat Pesanan Baru':'Buka Pembayaran'}</button></div><button className="secondary" onClick={()=>go('help')}>Bantuan Pembayaran</button></>:<><h3>Belum ada pesanan aktif</h3><p>Buat pesanan token terlebih dahulu.</p><button onClick={()=>go('choose')}>Beli Token</button></>}</>}
 {screen==='history'&&<><div className="ux-demo-empty">▤</div><h2>Belum ada transaksi selesai</h2><p>Pesanan yang belum dibayar tersedia di Pesanan Aktif.</p><button onClick={()=>go('active')}>Lihat Pesanan Aktif</button><button className="secondary" onClick={()=>go('help')}>Bantuan Pembayaran</button></>}
 {screen==='help'&&<><h2>Pahami status pesanan</h2><div className="ux-demo-card"><b>Menunggu pembayaran</b><p>Periksa nomor VA dan batas waktu sebelum membayar.</p><b>Kedaluwarsa</b><p>Masa pembayaran habis. Buat pesanan baru untuk melanjutkan.</p></div><p>Demo tidak menyatakan pembayaran berhasil atau token diterbitkan.</p><button onClick={()=>go('active')}>Kembali ke Pesanan</button></>}
 </div><div className="ux-demo-bottom"><button onClick={()=>go('home')}>Beranda</button><button onClick={()=>go('active')}>Pesanan</button><button onClick={()=>go('history')}>Riwayat</button></div></div></div>;
}
